# Generated by Django 4.2.11 on 2024-08-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0051_add_student_note_type_to_database_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_advanced_project',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('template_url', models.CharField(max_length=256)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='LearningAPI.project')),
            ],
        ),
    ]
